name: Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3 # Node.js 20 지원 버전으로 업데이트 가정
    - uses: docker/setup-buildx-action@v2 # Node.js 20 지원 버전으로 업데이트 가정
    - uses: docker/login-action@v2 # Node.js 20 지원 버전으로 업데이트 가정

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: yourusername/flaskapp:latest
    - name: Set output
      run: echo "VARIABLE_NAME=${{ env.VALUE }}" >> $GITHUB_ENV

