name: learn-github-actions
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */24 * * *' # 24마다 시간 실행
  workflow_dispatch:
    
jobs:
  python-hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - run: python -c "print('hello world')"
